import { Recipe } from "./types";

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "rec-1",
    title: "Shakshuka cu Brânză Feta și Ierburi",
    description: "O delicatesă mediteraneană cu ouă poșate într-un sos bogat de roșii coapte, ardei gras dulce, usturoi și condimente aromate, completată perfect de feta cremoasă.",
    imageUrl: "https://images.unsplash.com/photo-1590412200988-a436bb7050a4?auto=format&fit=crop&q=80&w=1000",
    category: "Mic Dejun",
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: "ușor",
    calories: 380,
    protein: 20,
    carbs: 15,
    fat: 25,
    isFavorite: true,
    ingredients: [
      "4 ouă ecologice proaspete",
      "1 conservă de roșii cuburi calitative (400g)",
      "1 ardei gras roșu mare, tăiat felii subțiri",
      "1 ceapă roșie medie, tocată mărunt",
      "2 căței de usturoi proaspăt, zdrobiți",
      "50g brânză feta sfărâmată",
      "1 linguriță de chimion măcinat",
      "1 linguriță de boia dulce afumată",
      "1/2 linguriță de fulgi de chili (opțional)",
      "2 linguri de ulei de măsline extra virgin",
      "Pătrunjel și coriandru proaspăt tocate",
      "Sare de mare și piper negru proaspăt măcinat"
    ],
    instructions: [
      "Încingeți uleiul de măsline într-o tigaie mare de fontă la foc mediu.",
      "Adăugați ceapa roșie și ardeiul gras. Sotați-le timp de 6-8 minute până când devin moi și ușor caramelizate.",
      "Adăugați usturoiul zdrobit, chimionul, boiaua afumată și fulgii de chili. Amestecați continuu timp de 1 minut până când mirodeniile își eliberează uleiurile aromatice.",
      "Turnați roșiile cuburi împreună cu sucul lor. Condimentați cu sare și piper, apoi lăsați sosul să fiarbă la foc mic timp de 10 minute pentru a se îngroșa.",
      "Folosiți o lingură mare pentru a crea 4 mici adâncituri în sosul de roșii fierbinte. Spargeți cu grijă fiecare ou direct în câte o adâncitură.",
      "Acoperiți tigaia cu un capac și gătiți la foc mic timp de 5-8 minute, până când albușul este complet opac, iar gălbenușul rămâne încă fluid.",
      "Luați tigaia de pe foc. Presărați brânza feta mărunțită, pătrunjelul și coriandrul proaspăt.",
      "Se servește imediat alături de pâine cu maia proaspăt prăjită."
    ],
    createdAt: "2026-06-15T08:00:00Z"
  },
  {
    id: "rec-2",
    title: "Paste Carbonara Clasice în Stil Roman",
    description: "Rețeta originală italiană fără smântână, bazată exclusiv pe cremozitatea emulsiei de ou proaspăt, brânză Pecorino Romano autentică și guanciale crocant.",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&q=80&w=1000",
    category: "Prânz",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "mediu",
    calories: 620,
    protein: 28,
    carbs: 65,
    fat: 26,
    isFavorite: true,
    ingredients: [
      "200g paște Spaghetti sau Rigatoni din grâu dur",
      "120g guanciale de calitate (sau pancetta afumată), tăiat cubulețe",
      "2 gălbenușuri de ou proaspete + 1 ou întreg",
      "75g brânză Pecorino Romano proaspăt răzuită (sau Parmigiano Reggiano)",
      "Mult piper negru proaspăt măcinat grosier",
      "Sare pentru apa pastelor (cu moderație)"
    ],
    instructions: [
      "Puneți la fiert o oală mare cu apă. Când dă în clocot, adăugați sare, apoi pastele și fierbeți-le conform instrucțiunilor de pe ambalaj până sunt 'al dente'.",
      "Între timp, într-o tigaie rece, adăugați guanciale tăiat fâșii subțiri. Puneți tigaia la foc mediu și lăsați grăsimea să se topească încet. Gătiți până când guanciale devine perfect crocant și auriu (aproximativ-7-8 minute). Opriți focul, dar păstrați tigaia caldă.",
      "Într-un bol mediu, bateți gălbenușurile cu oul întreg. Adăugați brânza Pecorino Romano răzuită fin și o cantitate generoasă de piper proaspăt măcinat. Amestecați energic până obțineți o pastă groasă și omogenă.",
      "Când pastele sunt gata, scoateți-le direct în tigaia cu guanciale și grăsimea topită, folosind un clește. Păstrați neapărat o cană din apa fierbinte în care au fiert pastele.",
      "Amestecați bine pastele în tigaie la foc foarte mic timp de jumătate de minut, asigurându-vă că sunt acoperite de grăsimea de la guanciale. Trageți tigaia complet de pe foc.",
      "Lăsați tigaia să se răcorească preț de 30 de secunde (pentru ca ouăle să nu se transforme în omletă!).",
      "Turnați amestecul de ou și brânză peste paste. Adăugați imediat aproximativ 4-5 linguri de apă caldă de pe paste și amestecați rapid și continuu de jos în sus.",
      "Continuați să amestecați energic timp de 1 minut, adăugând opțional încă puțină apă de la paste, până când sosul devine un sos fin, cremos și lucios care îmbracă perfect pastele.",
      "Distribuiți în farfurii adânci, presărați restul de guanciale foarte crocant de deasupra, încă puțin Pecorino și piper negru din belșug."
    ],
    createdAt: "2026-06-14T12:30:00Z"
  },
  {
    id: "rec-3",
    title: "Somon Glazat cu Soia, Miere și Asparang",
    description: "Somon fraged cu crustă caramelizată din miere, ghimbir și sos de soia, servit alături de sparanghel proaspăt pregătit la cuptor.",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=1000",
    category: "Cină",
    prepTime: 15,
    cookTime: 12,
    servings: 2,
    difficulty: "mediu",
    calories: 490,
    protein: 34,
    carbs: 18,
    fat: 28,
    isFavorite: false,
    ingredients: [
      "2 fileuri de somon proaspăt, cu piele (150-180g fiecare)",
      "250g sparanghel tânăr, cu capetele lemnoase îndepărtate",
      "3 linguri de sos de soia cu conținut redus de sare",
      "2 linguri de miere de albine pură",
      "1 cățel de usturoi fin răzuit",
      "1 linguriță de ghimbir proaspăt răzuit",
      "1 lingură de suc proaspăt de lămâie verde (lime)",
      "1 lingură de ulei de susan (sau ulei de măsline)",
      "1 linguriță de semințe de susan prăjite complet",
      "Ceapă verde feliată fin, pentru decor"
    ],
    instructions: [
      "Într-un bol mic, amestecați sosul de soia, mierea, usturoiul răzuit, ghimbirul proaspăt, sucul de lime și jumătate din uleiul de susan. Aceasta va fi glazura fină.",
      "Așezați fileurile de somon într-un vas plat și turnați peste ele jumătate din marinadă. Lăsați-le la marinat la temperatura camerei timp de 10-15 minute.",
      "Preîncălziți cuptorul la 200°C și tapetați o tavă de copt cu hârtie.",
      "Așezați sparanghelul într-o parte a tăvii, stropiți-l cu restul de ulei de măsline/susan, asezonați cu un praf de sare și amestecați bine pentru a-l acoperi uniform.",
      "Scoateți fileurile de somon din marinadă și așezați-le în cealaltă jumătate a tăvii, cu pielea în jos.",
      "Puneți tava în cuptor pentru 10-12 minute. La jumătatea timpului de gătire, ungeți somonul cu restul de marinadă/glazură rămasă pentru a crea acel luciu delicios.",
      "Setați funcția grill a cuptorului pentru ultimele 2 minute pentru a obține o caramelizare perfectă a marginilor.",
      "Verificați dacă somonul este fraged și se desface ușor cu furculița.",
      "Așezați somonul pe o farfurie alături de sulițele de sparanghel verde proaspăt. Stropiți deasupra sosul cald rămas în tavă și decorați cu susan prăjit și frunze fine de ceapă verde proaspătă."
    ],
    createdAt: "2026-06-13T19:00:00Z"
  },
  {
    id: "rec-4",
    title: "Sufleu Moale de Ciocolată Elegant (Fondant)",
    description: "Un desert clasic decadant, cu margini rumenite fin și o inimă topită de ciocolată neagră belgiană intensă care curge catifelat la prima tăietură.",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=1000",
    category: "Desert",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "dificil",
    calories: 420,
    protein: 8,
    carbs: 45,
    fat: 28,
    isFavorite: true,
    ingredients: [
      "100g ciocolată neagră belgiană (minim 70% cacao)",
      "100g unt cu 82% grăsime, plus suplimentar pentru uns formele",
      "2 ouă întregi de mărime medie + 2 gălbenușuri separate",
      "50g zahăr tos fin",
      "50g făină albă superioară cernută fin",
      "1 linguriță de extract pur de vanilie de Madagascar",
      "Un praf generos de sare de mare",
      "Pudră de cacao calitativă pentru pudrat formele",
      "Înghețată cremoasă de vanilie, fructe de pădure proaspete (pentru plating)"
    ],
    instructions: [
      "Preîncălziți cuptorul la 200°C cu funcția de ventilație pornită.",
      "Pregătiți formele ceramice (ramekin): ungeți-le generos cu unt topit folosind mișcări verticale de jos în sus (acest lucru ajută sufleul să crească uniform). Pudrați interiorul formelor cu pudră de cacao fină și îndepărtați excesul prin scuturare.",
      "Într-un bol termorezistent așezat peste o oală cu apă fierbinte (bain-marie), topiți ciocolata neagră mărunțită și untul. Amestecați delicat până când compoziția este perfect fină și lichidă. Lăsați bolul să se răcească ușor.",
      "Într-un alt bol mare, bateți ouăle întregi împreună cu gălbenușurile suplimentare și zahărul tos timp de 5 minute, folosind un mixer electric, până când își triplează volumul și compoziția devine cremoasă, deschisă la culoare.",
      "Turnați delicat ciocolata topită și extractul de vanilie peste spuma de ouă caldă, amestecând ușor cu o spatulă de silicon prin mișcări circulare largi pentru a menține aerul în compoziție.",
      "Încorporați sarea de mare și făina cernută în 2 tranșe, pliând delicat aluatul doar până când făina își pierde vizibilitatea.",
      "Distribuiți compoziția în mod egal în cele 4 forme pregătite (lăsați 1 cm liber de la marginea de sus).",
      "Coaceți la cuptor timp de exact 10-11 minute. Marginile sufleului trebuie să fie ferme și coapte, iar mijlocul să se clatine ușor.",
      "Lăsați ramekinu-rile să stea pe un grătar timp de 1 minut, apoi folosiți un cuțit subțire pe contur pentru desprindere. Răsturnați cu grijă sufleul cald direct pe farfuriile de desert elegante.",
      "Pudrați cu zahăr fin sau cacao și așezați alături o cupă mare de înghețată rece de vanilie și fructe roșii proaspete."
    ],
    createdAt: "2026-06-12T15:00:00Z"
  },
  {
    id: "rec-5",
    title: "Avocado Toast cu Ou Moale și Dukkah",
    description: "Pâine artizanală toastată cu maia, acoperită cu o pastă fină de avocado asezonată cu lime, ou poșat cu gălbenuș lichid și amestec crocant de semințe egiptene.",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=1000",
    category: "Mic Dejun",
    prepTime: 10,
    cookTime: 5,
    servings: 1,
    difficulty: "ușor",
    calories: 290,
    protein: 12,
    carbs: 20,
    fat: 22,
    isFavorite: false,
    ingredients: [
      "1 felie generoasă de pâine cu maia proaspătă",
      "1 avocado gata copt (soiul Hass)",
      "1 ou ecologic proaspăt",
      "1 linguriță de suc proaspăt de lămâie",
      "1 linguriță de Dukkah (amestec oriental de semințe de susan, coriandru, chimion și alune zdrobite)",
      "1 linguriță de ulei de măsline extra virgin",
      "Frunze mici de mentă sau rucola pentru decor",
      "Fulgii de sare Maldon și fulgi de chili"
    ],
    instructions: [
      "Prăjiți bine felia de pâine artizanală cu maia până când devine aurie și crocantă. Stropiți-o imediat cu jumătate din cantitatea de ulei de măsline fierbinte.",
      "Tăiați avocado în jumătate, îndepărtați sâmburele și scobiți miezul într-un bol. Zdrobiți-l grosier cu o furculiță, menținând câteva bucățele pentru textură.",
      "Adăugați imediat sucul proaspăt de lămâie (pentru a opri oxidarea), un deget de sare Maldon și jumătate de linguriță de ulei de măsline. Amestecați lejer.",
      "Pregătiți oul poșat (sau fiert la foc mic timp de 6 minute pentru a fi moale). Într-o oală mică cu apă clocotită și un strop de oțet alb, faceți un vârtej mic cu lingura și puneți oul proaspăt.",
      "Lăsați oul să se poșeze timp de exact 3 minute la foc foarte mic, apoi scoateți-l cu o spumieră pe un șervet absorbant de hârtie.",
      "Întindeți crema proaspătă de avocado în strat generos deasupra feliilor crocante de pâine caldă.",
      "Așezați oul poșat cu multă grijă exact în centrul stratului de avocado fin.",
      "Presărați amestecul crocant aromatic de Dukkah, câțiva fulgi fini de chili roșu, puțină sare extra fină de mare deasupra oului și ornați cu frunzulițe de rucola saut mentă proaspătă."
    ],
    createdAt: "2026-06-11T09:15:00Z"
  },
  {
    id: "rec-6",
    title: "Salată Vibrantă cu Smochine și Halloumi Gratinat",
    description: "O explozie de texturi și gusturi unice, îmbinând dulceața smochinelor proaspete, săratul specific al brânzei Halloumi la grătar și prospețimea rucolăi stropite cu reducție fină de rodie.",
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=1000",
    category: "Gustări",
    prepTime: 12,
    cookTime: 6,
    servings: 2,
    difficulty: "ușor",
    calories: 340,
    protein: 18,
    carbs: 15,
    fat: 24,
    isFavorite: false,
    ingredients: [
      "150g brânză Halloumi de primă calitate, feliată grosier la 1 cm",
      "4 smochine proaspete, bine coapte, tăiate în sferturi egale",
      "100g rucolă bio tânără, spălată și uscată",
      "40g sâmburi de nucă românească, rumeniți ușor în tigaie uscată",
      "1 lingură de reducție concentrată de oțet balsamic sau sirop de rodie",
      "2 linguri de ulei de măsline extra virgin presat la rece",
      "Semințe din jumătate de rodie aspră",
      "Sare grunjoasă de mare și piper roz zdrobit"
    ],
    instructions: [
      "Rumiți sâmburii de nuci într-o tigaie uscată la foc mediu timp de 2-3 minute pentru a-și activa gustul lemnos aromat. Tocat-le brut în bucăți măricele și puneți-le deoparte la răcit.",
      "În aceeași tigaie încinsă (fără grăsime suplimentară), adăugați feliile de brânză Halloumi. Coaceți-le timp de 2-3 minute pe fiecare parte, până când devin aurii și capătă acea crustă specifică de grill.",
      "Într-un bol mare de salată, refaceți prospețimea frunzelor de rucola. Adăugați miezul de nucă copt și amestecați ușor.",
      "Aranjați patul de rucola curat pe două farfurii de servire plate.",
      "Plasați feliile calde de brânză Halloumi direct deasupra frunzelor verzi, inserând estetic sferturile colorate de smochine proaspete.",
      "Distribuiți bobițele suculente de rodie roșie peste întreaga compoziție gata aranjată.",
      "Stropiți elegant totul cu ulei de măsline extra virgin și apoi cu mișcări circulare de reducție de oțet balsamic sau rodie.",
      "Asezonați cu un praf fin de sare de mare și asortați la final câteva boabe fine de piper roz zdrobit."
    ],
    createdAt: "2026-06-10T11:45:00Z"
  }
];
